import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/styles/main.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'min-h-screen flex flex-col items-center  ' + inter.className}>
        <header className="container flex items-center justify-between my-10">
          <h1 className="font-extrabold text-base sm:text-lg md:text-2xl  mr-auto">NEXT.JS AUTH</h1>  
          <nav>
            <Link
              href={`/`}
              className="text-white text-sm"
            >
              HOME
            </Link>
            <Link
              href={`/auth/login`}
              className="text-white text-sm ml-4"
            >LOGIN</Link>
          </nav>
        </header>
        <main className="flex flex-col items-center p-24 container">
          {children}
        </main> 
        <footer className="mt-auto py-4">
          <p className="text-center text-gray-500">© {new Date().getFullYear()} Next.js Auth | by <a target="__blank" href="https://juannunezblasco.es" className="">@juannunezblasco</a> </p> 
        </footer> 
      </body>
    </html>
  );
}
